"""create models

Revision ID: 21ea58fba8ce
Revises: 
Create Date: 2022-06-12 21:56:22.779371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "21ea58fba8ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_virtual_aliases_domain_id"),
        "virtual_aliases",
        ["domain_id"],
        unique=False,
    )
    op.add_column(
        "virtual_users",
        sa.Column("init_at", mysql.INTEGER(display_width=11), nullable=False),
    )
    op.add_column(
        "virtual_users",
        sa.Column("expire", mysql.INTEGER(display_width=11), nullable=False),
    )
    op.create_index(
        op.f("ix_virtual_users_domain_id"),
        "virtual_users",
        ["domain_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_virtual_users_domain_id"), table_name="virtual_users"
    )
    op.drop_column("virtual_users", "expire")
    op.drop_column("virtual_users", "init_at")
    op.drop_index(
        op.f("ix_virtual_aliases_domain_id"), table_name="virtual_aliases"
    )
    # ### end Alembic commands ###
