"""update models

Revision ID: 93c73ff5e10e
Revises: 21ea58fba8ce
Create Date: 2022-06-19 17:15:27.014670

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "93c73ff5e10e"
down_revision = "21ea58fba8ce"
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_virtual_users_domain_id", table_name="virtual_users")
    op.drop_table("virtual_users")
    op.drop_table("virtual_domains")
    op.drop_index("ix_virtual_aliases_domain_id", table_name="virtual_aliases")
    op.drop_table("virtual_aliases")
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_aliases",
        sa.Column("account_id", sa.String(50), nullable=False),
    )
    op.create_index(
        "ix_virtual_aliases_account_id",
        "virtual_aliases",
        ["account_id"],
        unique=False,
    )
    op.add_column(
        "virtual_users", sa.Column("account_id", sa.String(50), nullable=False)
    )
    op.create_index(
        "ix_virtual_users_account_id",
        "virtual_users",
        ["account_id"],
        unique=False,
    )
    op.add_column(
        "virtual_users",
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
    )
    op.create_table(
        "quota",
        sa.Column(
            "id",
            sa.Integer(),
            sa.PrimaryKeyConstraint("id"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("account_id", sa.String(50), nullable=False),
        sa.Column("email_limit", sa.Integer(), nullable=False, default=2),
        sa.Column(
            "custom_email_limit", sa.Integer(), nullable=False, default=0
        ),
        sa.Column("alias_limit", sa.Integer(), nullable=False, default=0),
    )
    # ### end Alembic commands ###
