"""update table virtual domain

Revision ID: c0cbd4508376
Revises: 93c73ff5e10e
Create Date: 2022-06-19 17:27:29.882437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c0cbd4508376"
down_revision = "93c73ff5e10e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_domains", sa.Column("type", sa.String(50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
